
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm install -g npm@5"
      - run:
          name: install-packages
          command: npm install
      - run:
          name: test
          command: npm run test