version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12.18.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@next'
      - run:
          name: install-packages
          command: npm install
      - run:
          name: test
          command: npm run test
